# Don't enforce any rules by default.
default: false

# Dollar signs are used before commands with output. 
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md014---dollar-signs-used-before-commands-without-showing-output 
MD014: true

# Headings should increment one level at a time.
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time
MD001: true

# Top heading should be a H1
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md002---first-heading-should-be-a-top-level-heading
MD002: true

# Ensure list indentation is consistent
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md005---inconsistent-indentation-for-list-items-at-the-same-level
MD005: true

# Hard tabs
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md010---hard-tabs
MD010: true

# Space required after heading character
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md018---no-space-after-hash-on-atx-style-heading
MD018: true
