version: 2.1

jobs:

  git_commits:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Test git commits
          command: make test

  markdownlint:
    docker:
      - image: tmknom/markdownlint:0.33.0
    steps:
      - checkout

      # Note, we can't use a make target here as `make` isn't installed on this Docker image.
      - run:
          name: Lint content with markdownlint
          command: markdownlint .

workflows:
  static-analysis:
    jobs:
      - git_commits
      - markdownlint
